name: pipeline

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]
  push:
    branches: [main, dev]

env:
  TF_WORKING_DIR: "infra/terraform/environments/${{ (github.ref_name == 'main' || github.base_ref == 'main') && 'prod' || 'dev' }}"
  ENVIRONMENT: "${{ (github.ref_name == 'main' || github.base_ref == 'main') && 'prod' || 'dev' }}"
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    environment: ${{ github.event_name == 'push' && ((github.ref_name == 'main' && 'prod') || (github.ref_name == 'dev' && 'dev')) || null }}

    outputs:
      ecs_task_definition_arn: ${{ steps.tf_outputs.outputs.ecs_task_definition_arn }}
      ecs_cluster_name: ${{ steps.tf_outputs.outputs.ecs_cluster_name }}
      ecs_service_name: ${{ steps.tf_outputs.outputs.ecs_service_name }}
      alb_dns: ${{ steps.tf_outputs.outputs.alb_dns }}
      ecr_repository_url: ${{ steps.tf_outputs.outputs.ecr_repository_url }}
      ecs_task_execution_role_arn: ${{ steps.tf_outputs.outputs.ecs_task_execution_role_arn }}
            

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Format e Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -no-color -out=tfplan.binary > plan_output.txt
          
      - name: Plan para PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('${{ env.TF_WORKING_DIR }}/plan_output.txt', 'utf8');

            const comment = `${{ env.ENVIRONMENT }}

              <details>
              <summary>plan</summary>

              \`\`\`
              ${plan}
              \`\`\`

              </details>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve

      - name: Extract Outputs
        id: tf_outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "ecs_task_definition_arn=$(terraform output -raw ecs_task_definition_arn)" >> $GITHUB_OUTPUT
          echo "ecs_cluster_name=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_OUTPUT
          echo "ecs_service_name=$(terraform output -raw ecs_service_name)" >> $GITHUB_OUTPUT
          echo "alb_dns=$(terraform output -raw alb_dns_name)" >> $GITHUB_OUTPUT
          echo "ecr_repository_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "ecs_task_execution_role_arn=$(terraform output -raw ecs_task_execution_role_arn)" >> $GITHUB_OUTPUT
          

  build_and_deploy:
    name: Build e Deploy
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'push'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login na ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Builda e Push imagem
        env:
          ECR_URL: ${{ needs.terraform.outputs.ecr_repository_url }}
          IMG_TAG: ${{ env.ENVIRONMENT }}
          SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${SHA::7}
          docker build -t backend:$SHORT_SHA -f docker/backend/Dockerfile .
          docker tag backend:$SHORT_SHA $ECR_URL:$SHORT_SHA
          docker tag backend:$SHORT_SHA $ECR_URL:$IMG_TAG
          docker push $ECR_URL:$SHORT_SHA
          docker push $ECR_URL:$IMG_TAG
          echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV

      - name: Register new Task Definition and Deploy
        env:
          CLUSTER: ${{ needs.terraform.outputs.ecs_cluster_name }}
          SERVICE: ${{ needs.terraform.outputs.ecs_service_name }}
          ECR_REPO: ${{ needs.terraform.outputs.ecr_repository_url }}
          EXEC_ROLE: ${{ needs.terraform.outputs.ecs_task_execution_role_arn }}

        run: |
          IMAGE="${ECR_REPO}:${IMAGE_TAG}"

          echo "IMAGE=$IMAGE"
          echo "EXEC_ROLE=$EXEC_ROLE"

          sed -e "s|IMAGE_PLACEHOLDER|$IMAGE|" \
          -e "s|EXECUTION_ROLE_ARN|$EXEC_ROLE|" \
          .github/workflows/task-definition.json > new-task-def.json

          TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://new-task-def.json \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)


          aws ecs update-service \
          --cluster $CLUSTER \
          --service $SERVICE \
          --task-definition $TASK_DEF_ARN

      - name: Deployment Summary
        run: |
          echo "Deploy Summary " >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
          echo "- **ALB URL**: [http://${{ needs.terraform.outputs.alb_dns }}](http://${{ needs.terraform.outputs.alb_dns }})" >> $GITHUB_STEP_SUMMARY