name: Build and Push to ECR

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t backend:$IMAGE_TAG -f docker/backend/Dockerfile .

      - name: Tag image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devopsprojectgiancarlo-dev-backend

          docker tag backend:$IMAGE_TAG $IMAGE_URI:$IMAGE_TAG
          docker tag backend:$IMAGE_TAG $IMAGE_URI:dev

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devopsprojectgiancarlo-dev-backend:$IMAGE_TAG


      - name: Render task definition
        run: |
          sed -e "s|IMAGE_URI|${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devopsprojectgiancarlo-dev-backend:$IMAGE_TAG|" \
              -e "s|EXECUTION_ROLE_ARN|${{ secrets.ECS_EXECUTION_ROLE_ARN }}|" \
              .github/workflows/ecs-task-def.json > task-def.json

      - name: Deploy to ECS
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://task-def.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          aws ecs update-service \
            --cluster devopsprojectgiancarlo-dev-cluster \
            --service devopsprojectgiancarlo-dev-service \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: ALB URL
        working-directory: infra/terraform/environments/dev
        run: |
          terraform init -input=false
          ALB=$(terraform output -raw alb_dns_name)

          echo "=================================="
          echo " Deploy bala realizado!"
          echo "   URL: http://$ALB"
          echo "=================================="